[package]
name = "work_with_data"
version = "0.1.0"
edition = "2021"
authors = ["Yura <leonyvb04@Ggmail.com> Batazov"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
